version: '3.3'
services:
    nginx:
        build: './docker/nginx'
        volumes:
            - "./docker/nginx/dist:/usr/share/nginx/html"
        ports:
            - '80:80'
        networks:
            - webpj
    
    springboot:
        build: './docker/springboot'
        networks:
            - webpj
    
    mysql:
        image: mysql:5.6
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_DATABASE: 'webpj'
            MYSQL_USER: 'gallery'
            MYSQL_PASSWORD: '20190621'
        networks:
            - webpj

    socket:
        build: './docker/socket'
        networks:
            - webpj
        ports:
            - '3000:3000'

networks:
    webpj: